title: "Balamurugan Maruthavanan"
description: "DevSecOps Engineer | Azure | Kubernetes | Security Automation"
theme: jekyll-theme-slate
show_downloads: false
github:
  is_project_page: false

include:
  - assets/css/custom.css
